app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.home, name="home"),
    path('blogs', views.blogs, name="blogs"),
    path('article/<int:pk>', views.blog_article, name="article"),
    path('post-blog', views.blog_register, name="post-blog"),
    path('post', views.make_a_post, name="post"),
    path('profile', views.profile, name='profile'),
    path('edit_blog/<int:pk>', views.edit_blog, name='edit_blog'),
    # path('login', views.user_login, name='login'),
    # path('signin', views.signin, name='signin'),
]

authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"

urlpatterns = [
    path('login', views.user_login, name='login'),
    path('home', views.logout_view, name='logout'),
    path('signup', views.user_register, name='signup'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('social-auth/', include('social_django.urls', namespace='social-auth')),
    
    path('', include('authentication.urls')),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/templates/includes/header.html
<nav
  class="blog-nav rounded-lg border shadow-lg overflow-hidden p-2 bg-white border-stone-200 shadow-stone-950/5 mx-auto w-full max-w-screen-xl mb-3">
  <div class="flex items-center">
    <a href="{% url 'app:home' %}"
      class="font-sans antialiased text-sm text-current ml-2 mr-2 block py-1 font-semibold">Project Factorio</a>
    <hr class="mx-1 hidden h-5 w-px border-l border-t-0 border-secondary-dark lg:block" />
    <div class="hidden lg:block">
      <ul class="min-w-60 mt-4 flex flex-col gap-1 lg:mt-0 lg:flex-row lg:items-center">

        <!-- Blogs -->
        <a href="{% url 'app:blogs' %}"
          class="flex items-center py-1.5 px-2.5 rounded-md align-middle select-none font-sans transition-all duration-300 ease-in aria-disabled:opacity-50 aria-disabled:pointer-events-none bg-transparent text-stone-600 hover:bg-stone-200 focus:bg-stone-200 focus:text-stone-800 dark:focus:text-white dark:data-[selected=true]:text-white dark:bg-opacity-70">
          <span class="grid place-items-center shrink-0 me-2.5 mr-1.5"><svg width="1.5em" height="1.5em"
              stroke-width="1.5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="currentColor"
              class="h-4 w-4">
              <path
                d="M21 7.35304L21 16.647C21 16.8649 20.8819 17.0656 20.6914 17.1715L12.2914 21.8381C12.1102 21.9388 11.8898 21.9388 11.7086 21.8381L3.30861 17.1715C3.11814 17.0656 3 16.8649 3 16.647L2.99998 7.35304C2.99998 7.13514 3.11812 6.93437 3.3086 6.82855L11.7086 2.16188C11.8898 2.06121 12.1102 2.06121 12.2914 2.16188L20.6914 6.82855C20.8818 6.93437 21 7.13514 21 7.35304Z"
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
              <path d="M3.52844 7.29357L11.7086 11.8381C11.8898 11.9388 12.1102 11.9388 12.2914 11.8381L20.5 7.27777"
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
              <path d="M12 21L12 12" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
              <path
                d="M11.6914 11.8285L3.89139 7.49521C3.49147 7.27304 3 7.56222 3 8.01971V16.647C3 16.8649 3.11813 17.0656 3.30861 17.1715L11.1086 21.5048C11.5085 21.727 12 21.4378 12 20.9803V12.353C12 12.1351 11.8819 11.9344 11.6914 11.8285Z"
                fill="currentColor" stroke="currentColor" stroke-linejoin="round"></path>
            </svg>
          </span>
          <small class="font-sans antialiased text-sm text-current">Blogs</small>
        </a>
        <!-- Form  -->
        {% if request.user.is_authenticated %}
        <a href="{% url 'app:post' %}"
          class="flex items-center py-1.5 px-2.5 rounded-md align-middle select-none font-sans transition-all duration-300 ease-in aria-disabled:opacity-50 aria-disabled:pointer-events-none bg-transparent text-stone-600 hover:bg-stone-200 focus:bg-stone-200 focus:text-stone-800 dark:focus:text-white dark:data-[selected=true]:text-white dark:bg-opacity-70">
          <span class="grid place-items-center shrink-0 me-2.5 mr-1.5"><svg width="1.5em" height="1.5em"
              stroke-width="1.5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="currentColor"
              class="h-4 w-4">
              <path d="M7 6L17 6" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
              <path d="M7 9L17 9" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
              <path d="M9 17H15" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
              <path
                d="M3 12H2.6C2.26863 12 2 12.2686 2 12.6V21.4C2 21.7314 2.26863 22 2.6 22H21.4C21.7314 22 22 21.7314 22 21.4V12.6C22 12.2686 21.7314 12 21.4 12H21M3 12V2.6C3 2.26863 3.26863 2 3.6 2H20.4C20.7314 2 21 2.26863 21 2.6V12M3 12H21"
                stroke="currentColor"></path>
            </svg>
          </span>
          <small class="font-sans antialiased text-sm text-current">Post</small>
        </a>
        {% endif %}
        <!-- Profile -->
        {% if request.user.is_authenticated %}
        <a href="{% url 'app:profile' %}"
          class="flex items-center py-1.5 px-2.5 rounded-md align-middle select-none font-sans transition-all duration-300 ease-in aria-disabled:opacity-50 aria-disabled:pointer-events-none bg-transparent text-stone-600 hover:bg-stone-200 focus:bg-stone-200 focus:text-stone-800 dark:focus:text-white dark:data-[selected=true]:text-white dark:bg-opacity-70">
          <span class="grid place-items-center shrink-0 me-2.5 mr-1.5"><svg width="1.5em" height="1.5em"
              stroke-width="1.5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="currentColor"
              class="h-4 w-4">
              <path
                d="M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2Z"
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
              <path d="M4.271 18.3457C4.271 18.3457 6.50002 15.5 12 15.5C17.5 15.5 19.7291 18.3457 19.7291 18.3457"
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
              <path
                d="M12 12C13.6569 12 15 10.6569 15 9C15 7.34315 13.6569 6 12 6C10.3431 6 9 7.34315 9 9C9 10.6569 10.3431 12 12 12Z"
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
            </svg>
          </span>
          <small class="font-sans antialiased text-sm text-current">Acount</small>
        </a>
        {% else %}
        <a href="{% url 'authentication:login' %}"
          class="flex items-center py-1.5 px-2.5 rounded-md align-middle select-none font-sans transition-all duration-300 ease-in aria-disabled:opacity-50 aria-disabled:pointer-events-none bg-transparent text-stone-600 hover:bg-stone-200 focus:bg-stone-200 focus:text-stone-800 dark:focus:text-white dark:data-[selected=true]:text-white dark:bg-opacity-70">
          <span class="grid place-items-center shrink-0 me-2.5 mr-1.5"><svg width="1.5em" height="1.5em"
              stroke-width="1.5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="currentColor"
              class="h-4 w-4">
              <path
                d="M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2Z"
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
              <path d="M4.271 18.3457C4.271 18.3457 6.50002 15.5 12 15.5C17.5 15.5 19.7291 18.3457 19.7291 18.3457"
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
              <path
                d="M12 12C13.6569 12 15 10.6569 15 9C15 7.34315 13.6569 6 12 6C10.3431 6 9 7.34315 9 9C9 10.6569 10.3431 12 12 12Z"
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
            </svg>
          </span>
          <small class="font-sans antialiased text-sm text-current">Acount</small>
        </a>
        {% endif %}
        <!-- Admin -->
        
        <a href="/admin/"
          class="flex items-center py-1.5 px-2.5 rounded-md align-middle select-none font-sans transition-all duration-300 ease-in aria-disabled:opacity-50 aria-disabled:pointer-events-none bg-transparent text-stone-600 hover:bg-stone-200 focus:bg-stone-200 focus:text-stone-800 dark:focus:text-white dark:data-[selected=true]:text-white dark:bg-opacity-70">
          <span class="grid place-items-center shrink-0 me-2.5 mr-1.5"><i class="fa-solid fa-gear h-4 w-4"></i>
          </span>
          <small class="font-sans antialiased text-sm text-current">Admin</small>
        </a>
        
      </ul>
    </div>
    <button
      class="place-items-center border align-middle select-none font-sans font-medium text-center transition-all duration-300 ease-in disabled:opacity-50 disabled:shadow-none disabled:pointer-events-none text-sm min-w-[34px] min-h-[34px] rounded-md bg-transparent border-transparent text-stone-800 hover:bg-stone-200/10 hover:border-stone-600/10 shadow-none hover:shadow-none ml-auto mr-2 grid lg:hidden"><svg
        width="1.5em" height="1.5em" stroke-width="1.5" viewBox="0 0 24 24" fill="none"
        xmlns="http://www.w3.org/2000/svg" color="currentColor" class="h-4 w-4">
        <path d="M3 5H21" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
        <path d="M3 12H21" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
        <path d="M3 19H21" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
      </svg>
    </button>
    {% if request.user.is_authenticated %}

      {% if request.user.profile %}

    <a href="{% url 'app:profile' %}" class="inline-block outline-none group lg:ml-auto">
      <img aria-expanded="false" aria-haspopup="menu" src="{{ request.user.profile_photo.url }}" alt="profile-picture"
        class=" object-cover object-center w-9 h-9 rounded outline-none group border border-stone-400 p-0.5 lg:ml-auto rounded-full" />
    </a>{% endif %}

    {% else %}
    <a href="{% url 'authentication:login' %}" class="inline-block outline-none group lg:ml-auto">
      <img aria-expanded="false" aria-haspopup="menu" src="https://avatar.iran.liara.run/public" alt="profile-picture"
        class=" object-cover object-center w-9 h-9 rounded outline-none group border border-stone-400 p-0.5 lg:ml-auto rounded-full" />
    </a>
    {% endif %}
  </div>

</nav>
</div>