app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.home, name="home"),
    path('blogs', views.blogs, name="blogs"),
    path('article/<int:pk>', views.blog_article, name="article"),
    path('post-blog', views.blog_register, name="post-blog"),
    path('post', views.make_a_post, name="post"),
    path('profile', views.profile, name='profile'),
    path('edit_blog/<int:pk>', views.edit_blog, name='edit_blog'),
    # path('login', views.user_login, name='login'),
    # path('signin', views.signin, name='signin'),
]

authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"

urlpatterns = [
    path('login', views.user_login, name='login'),
    path('home', views.logout_view, name='logout'),
    path('signup', views.user_register, name='signup'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('social-auth/', include('social_django.urls', namespace='social-auth')),
    
    path('', include('authentication.urls')),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href= {% static 'css/style.css' %}>
    {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"> {% endcomment %}
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>    
    {% include 'includes/header.html' %}

    {% block content %}
    
    {% endblock %}
</body>
</html>

app/templates/blog_post.html
{% extends "base.html" %} {% block content %}

<div class="max-w-screen-xl mx-auto p-6 bg-white rounded-lg shadow-md">
  <!-- Cabeçalho com botão de voltar -->
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-2xl font-bold">{{ post.title }}</h1>
    <a href="{% url 'app:blogs' %}"
      class="inline-flex items-center justify-center border align-middle select-none font-sans font-medium text-center duration-300 ease-in disabled:opacity-50 disabled:shadow-none disabled:cursor-not-allowed focus:shadow-none text-sm py-2 px-4 shadow-sm hover:shadow-md bg-stone-800 hover:bg-stone-700 relative bg-gradient-to-b from-stone-700 to-stone-800 border-stone-900 text-stone-50 rounded-lg hover:bg-gradient-to-b hover:from-stone-800 hover:to-stone-800 hover:border-stone-900 after:absolute after:inset-0 after:rounded-[inherit] after:box-shadow after:shadow-[inset_0_1px_0px_rgba(255,255,255,0.25),inset_0_-2px_0px_rgba(0,0,0,0.35)] after:pointer-events-none transition antialiased">
      Voltar
    </a>
  </div>

  <div>
    <!-- Imagem do artigo https://i.ytimg.com/vi/QzG_ITr3VfQ/maxresdefault.jpg-->
    {% if post.thumbnail %}
    <img src="{{ post.thumbnail.url }}" alt="{{ post.title }}" class="w-96 h-auto rounded-lg mb-6" />
    {% else %}
    <img src="https://i.ytimg.com/vi/QzG_ITr3VfQ/maxresdefault.jpg" alt="Thumbnail padrão"
      class="w-96 h-auto rounded-lg mb-6" />
    {% endif %}
  </div>

  <!-- Data e author -->
  <div>
    <div class="text-sm text-gray-500 mb-4">
      <p>
        Escrito por
        {% if post.is_anonymous or post.author == None %}
        <span class="font-semibold">Anônimo</span>
        {% else %}
        <span class="font-semibold">{{ post.author }}</span>
        {% endif %} em {{ post.create_at|date:"F d" }}
      </p>
    </div>

    <!-- Conteúdo do artigo -->
    <article class="text-lg leading-relaxed space-y-4">
      <p>{{post.content}}</p>
    </article>
  </div>

</div>

{% endblock %}

app/templates/blogs.html
{% extends "base.html" %}
{% block content %}



<div class="blog-grid max-w-screen-xl mx-auto">

    {% comment %} {% for post in object_list %} {% endcomment %}
    {% for post in posts %}


    <a href="{% url 'app:article' post.pk %}" class="feature" style="text-decoration: none;">
  
        <div class="w-full h-full rounded-lg border shadow-sm bg-white border-stone-200 shadow-stone-950/5 max-w-[24rem] overflow-hidden">
            
            <div class="flex justify-center">
                {% if post.thumbnail %}
                    <div class="w-full h-48 overflow-hidden rounded m-2">
                        <img src="{{ post.thumbnail.url }}" alt="ui/ux review check" class="w-full h-full object-cover object-top" />
                    </div>
                {% else %}
                    <div class="w-full h-48 overflow-hidden rounded m-2">
                        <img src="https://assets.nintendo.com/image/upload/q_auto/f_auto/ncom/software/switch/70010000056818/c700b4cc22a81c2099335d83fe379e9cdc6afd190a9985f74ba8f7e589f4ffd2" alt="default thumbnail" class="w-full h-full object-cover object-top" />
                    </div>
                {% endif %}
            </div>
            

            <!-- Título e resumo da postagem -->
        
                <div class="w-full h-max rounded px-3.5 py-2.5">
                    <h6 class="font-sans antialiased font-bold text-base md:text-lg lg:text-xl text-current line-clamp-1">{{ post.title }}</h6>
                    <p class="font-sans antialiased text-base mt-1 text-stone-600 line-clamp-1">{{ post.content }}</p>
                </div>
                <div class="w-full px-3.5 pt-2 pb-3.5 rounded mt-4 flex items-center justify-between">

                    <!-- Profiles dos usuarios que leram o post TODO -->
                    <div class="flex items-center -space-x-3">
                        <button class="outline-none group">
                            <img src="https://t3.ftcdn.net/jpg/06/95/84/12/360_F_695841244_ahT1GEYsQjjomgyiDUjAlOLfpRD5fjso.jpg" alt="natali craig" class="inline-block object-cover object-center w-9 h-9 rounded border-2 border-stone-200 hover:z-10" />
                        </button>
                        <button class="outline-none group">
                            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9pfBaCNEmCGbuDML0VO-8mBAIDjTZrWq8Gw&s" alt="tania andrew" class="inline-block object-cover object-center w-9 h-9 rounded border-2 border-stone-200 hover:z-10" />
                        </button>
                    </div>

                    <!-- Contador de views e data de publicação -->
                    <small class="font-sans antialiased text-sm text-current">Views: {{ post.views }}</small>
                    <small class="font-sans antialiased text-sm text-current">{{ post.create_at|date:"F d" }}</small>
                </div>
          
        </div>
    </a>  
    {% endfor %}
</div>
{% endblock %}

app/templates/edit_blog.html
{% extends "base.html" %}
{% block content %}


<div class="max-w-screen-xl mx-auto">
    <form action="" method="post" enctype="multipart/form-data" class="my-5">
        {% csrf_token %}
        <div class="px-5">
            <div class=" grid grid-cols-1 md:grid-cols-2 gap-10">
                <div>
                    <!-- Campo Título -->
                    <label
                        class="block font-sans text-lg text-stone-800 dark:text-black font-semibold mb-2">Título</label>
                    <div class="relative w-full custom-form mb-2">
                        {{ forms.title }}
                    </div>

                    <!-- Campo Post -->
                    <label
                        class="block font-sans text-lg text-stone-800 dark:text-black font-semibold mb-2">Post</label>
                    <div class="relative w-full custom-form mb-2">
                        {{ forms.content }}
                    </div>

                    <!-- Escolha de postagem anônima -->
                    <div class="flex items-center mb-2">
                        <input type="checkbox" id="anonymous" name="anonymous" class="mr-2" {% if blog.is_anonymous %}
                            checked {% endif %}>
                        <label class="font-sans text-sm text-stone-600 dark:text-black font-medium">Postar de forma
                            anônima</label>
                    </div>

                </div>

                <div>
                    <!-- Campo Thumbnail -->
                    <label
                        class="block font-sans text-lg text-stone-800 dark:text-black font-semibold mb-2">Thumbnail</label>
                    <div class="relative w-full mb-6">
                        {{ forms.thumbnail }}
                        {% if blog.thumbnail %}
                        <img src="{{ blog.thumbnail.url }}"
                            class="w-full h-64 object-cover my-5 rounded-lg shadow-sm object-top" alt="thumbnail">
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Botão de envio e cancelar -->
        <div class="flex space-x-2 mt-4 px-5">
            <button type="submit"
                class="inline-flex items-center justify-center border align-middle select-none font-sans font-medium text-center duration-300 ease-in disabled:opacity-50 disabled:shadow-none disabled:cursor-not-allowed focus:shadow-none text-sm py-2 px-4 shadow-sm hover:shadow-md bg-stone-800 hover:bg-stone-700 relative bg-gradient-to-b from-stone-700 to-stone-800 border-stone-900 text-stone-50 rounded-lg hover:bg-gradient-to-b hover:from-stone-800 hover:to-stone-800 hover:border-stone-900 after:absolute after:inset-0 after:rounded-[inherit] after:box-shadow after:shadow-[inset_0_1px_0px_rgba(255,255,255,0.25),inset_0_-2px_0px_rgba(0,0,0,0.35)] after:pointer-events-none transition antialiased">
                Enviar
            </button>
            <a href="{% url 'app:profile' %}"
                class="inline-flex items-center justify-center border align-middle select-none font-sans font-medium text-center duration-300 ease-in disabled:opacity-50 disabled:shadow-none disabled:cursor-not-allowed focus:shadow-none text-sm py-2 px-4 shadow-sm hover:shadow-md bg-red-950 hover:bg-red-800 relative bg-gradient-to-b from-red-900 to-red-950 border-red-950 text-stone-50 rounded-lg hover:bg-gradient-to-b hover:from-red-850 hover:to-red-900 hover:border-red-900 after:absolute after:inset-0 after:rounded-[inherit] after:box-shadow after:shadow-[inset_0_1px_0px_rgba(255,255,255,0.25),inset_0_-2px_0px_rgba(0,0,0,0.35)] after:pointer-events-none transition antialiased">
                Cancelar
            </a>
        </div>

    </form>
</div>



{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% block content %}



<div
  class="rounded-lg border shadow-sm bg-white border-stone-200 shadow-stone-950/5 relative flex h-[calc(100vh-6rem)] w-full flex-col items-end justify-center overflow-hidden text-center max-w-screen-xl mx-auto">
  <div class="h-max rounded m-2">
    <div
      class="absolute inset-0 m-0 h-full w-full rounded-none bg-[url('https://thunderkeys.com/cdn/shop/files/Factorio_4.jpg?v=1717498098&width=1920')] bg-cover bg-center">
      <div
        class="absolute inset-0 h-full w-full bg-gradient-to-t from-black/80 via-black/50 to-black/10 dark:from-black/90 dark:via-black/60 dark:to-black/20">
      </div>
    </div>
  </div>
  <div class="w-full rounded relative bottom-0 flex h-full flex-col items-center justify-center px-6 py-14 md:px-12">
    <h4 class="font-sans antialiased font-bold text-xl md:text-2xl lg:text-3xl text-white">Automação sem limites,
      estratégia sem igual</h4>
    <h6 class="font-sans antialiased font-bold text-base md:text-lg lg:text-xl my-6 text-white/80">Helder G. G.</h6>
  </div>
</div>

{% endblock %}

app/templates/post_article.html
{% extends "base.html" %}
{% block content %}

<div class="max-w-screen-xl mx-auto">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-10">
        <!-- Formulário -->
        <form action="{% url 'app:post-blog' %}" method="post" enctype="multipart/form-data" class="my-5">
            {% csrf_token %}

            <!-- Campo Título -->
            <label class="block font-sans text-lg text-stone-800 dark:text-black font-semibold mb-2">Título</label>
            <div class="relative w-full custom-form mb-2">
                {{ forms.title }}
            </div>

            <!-- Campo Post -->
            <label class="block font-sans text-lg text-stone-800 dark:text-black font-semibold mb-2">Post</label>
            <div class="relative w-full custom-form mb-2">
                {{ forms.content }}
            </div>

            <!-- Campo Thumbnail -->
            <label class="block font-sans text-lg text-stone-800 dark:text-black font-semibold mb-2">Thumbnail</label>
            <div class="relative w-full mb-2">
                {{ forms.thumbnail }}
            </div>

            <!-- Escolha de postagem anônima -->
            <div class="flex items-center mb-2">
                <input type="checkbox" id="anonymous" name="anonymous" class="mr-2">
                <label class="font-sans text-sm text-stone-600 dark:text-black font-medium">
                    Postar de forma anônima
                </label>
            </div>

            <!-- Botões de envio e cancelar -->
            <div class="flex space-x-2">
                <button type="submit"
                    class="inline-flex items-center justify-center border align-middle select-none font-sans font-medium text-center duration-300 ease-in disabled:opacity-50 disabled:shadow-none disabled:cursor-not-allowed focus:shadow-none text-sm py-2 px-4 shadow-sm hover:shadow-md bg-stone-800 hover:bg-stone-700 relative bg-gradient-to-b from-stone-700 to-stone-800 border-stone-900 text-stone-50 rounded-lg hover:bg-gradient-to-b hover:from-stone-800 hover:to-stone-800 hover:border-stone-900 after:absolute after:inset-0 after:rounded-[inherit] after:box-shadow after:shadow-[inset_0_1px_0px_rgba(255,255,255,0.25),inset_0_-2px_0px_rgba(0,0,0,0.35)] after:pointer-events-none transition antialiased">
                    Enviar
                </button>
                <a href="{% url 'app:blogs' %}"
                    class="inline-flex items-center justify-center border align-middle select-none font-sans font-medium text-center duration-300 ease-in disabled:opacity-50 disabled:shadow-none disabled:cursor-not-allowed focus:shadow-none text-sm py-2 px-4 shadow-sm hover:shadow-md bg-red-950 hover:bg-red-800 relative bg-gradient-to-b from-red-900 to-red-950 border-red-950 text-stone-50 rounded-lg hover:bg-gradient-to-b hover:from-red-850 hover:to-red-900 hover:border-red-900 after:absolute after:inset-0 after:rounded-[inherit] after:box-shadow after:shadow-[inset_0_1px_0px_rgba(255,255,255,0.25),inset_0_-2px_0px_rgba(0,0,0,0.35)] after:pointer-events-none transition antialiased">
                    Cancelar
                </a>
            </div>
        </form>

        <!-- Imagem -->
        <div class="my-auto hidden md:block">
            <img src="https://i.redd.it/buutovko6k1a1.gif" alt="Imagem ilustrativa" class="rounded-lg shadow-sm">
        </div>
    </div>
</div>

{% endblock %}

app/templates/profile.html
{% extends "base.html" %} {% block content %}
  <div class="max-w-screen-xl mx-auto">
    <div class="grid grid-cols-3 gap-5">
      <div class="container mx-auto flex justify-center items-start h-screen">
        <div
          class="bg-white shadow-xl rounded-2xl p-6 flex flex-col items-center w-full"
        >
          <div class="sticky ml-auto">
            <form method="post" action="{% url 'authentication:logout' %}" class="text-center inline-flex border align-middle select-none font-sans font-medium text-center duration-300 ease-in disabled:opacity-50 disabled:shadow-none disabled:cursor-not-allowed focus:shadow-none text-sm shadow-sm hover:shadow-md bg-red-950 hover:bg-red-800 relative bg-gradient-to-b from-red-900 to-red-950 border-red-950 text-stone-50 rounded-full hover:bg-gradient-to-b hover:from-red-850 hover:to-red-900 hover:border-red-900 after:absolute after:inset-0 after:rounded-[inherit] after:box-shadow after:shadow-[inset_0_1px_0px_rgba(255,255,255,0.25),inset_0_-2px_0px_rgba(0,0,0,0.35)] after:pointer-events-none transition antialiased">
              {% csrf_token %}
              <button type="submit" class="rounded w-8 h-8">
                <i class="fa-solid fa-person-running text-xl"></i>
              </button>
            </form>
          </div>
          <div
            class="w-32 h-32 rounded-full overflow-hidden border-4 border-gray-300 mb-4"
          >
            {% if request.user.profile_photo %}

            <img
              src="{{ request.user.profile_photo.url}}"
              alt="profile image"
              class="w-full h-full object-cover"
            />

            {% else %}

            <img
              src="https://placehold.co/150x100"
              alt="Foto do Perfil"
              class="w-full h-full object-cover"
            />

            {% endif %}
          </div>
          <h2 class="text-2xl font-bold text-gray-800">
            {% if request.user.first_name %} 
              {{ request.user.first_name }} {{request.user.last_name }} 
            {% else %} 
            {{ request.user.username }} 
            {% endif %}
          </h2>
          <h5 class="font-bold text-gray-800">{{ request.user.email }}</h5>
          <p class="text-gray-600 text-center mt-2">{{ request.user.bio }}</p>
          <div class="mt-4 space-x-4">
            <button
              class="inline-flex items-center justify-center border align-middle select-none font-sans font-medium text-center duration-300 ease-in disabled:opacity-50 disabled:shadow-none disabled:cursor-not-allowed focus:shadow-none text-sm py-2 px-4 shadow-sm hover:shadow-md bg-stone-800 hover:bg-stone-700 relative bg-gradient-to-b from-stone-700 to-stone-800 border-stone-900 text-stone-50 rounded-lg hover:bg-gradient-to-b hover:from-stone-800 hover:to-stone-800 hover:border-stone-900 after:absolute after:inset-0 after:rounded-[inherit] after:box-shadow after:shadow-[inset_0_1px_0px_rgba(255,255,255,0.25),inset_0_-2px_0px_rgba(0,0,0,0.35)] after:pointer-events-none transition antialiased"
            >
              Editar
            </button>
            <span
              class="bg-gray-100 text-gray-700 py-2 px-4 rounded-lg hover:bg-gray-200 transition"
            >
              Postagens: {{ request.user.blog_count }}
            </span>
          </div>
          <div class="w-full mt-6">
            <h3 class="text-lg font-semibold text-gray-800 mb-2">Sobre</h3>
            <p class="text-gray-600 text-sm text-justify">
              {{ request.user.bio_details }}
            </p>
          </div>
        </div>
      </div>

      <div class="h-fit col-span-2 overflow-hidden rounded-lg shadow-md">
        <table
          class="table-auto min-w-full w-full border-collapse border rounded-xl"
        >
          <thead class="text-xs text-gray-50 uppercase bg-stone-700">
            <tr>
              <th scope="col" class="px-2 py-2">Título</th>
              <th scope="col" class="px-2 py-2">Anônimo</th>
              <th scope="col" class="px-2 py-2">Imagem</th>
              <th scope="col" class="px-2 py-2">Data de Criação</th>
              <th scope="col" class="px-2 py-2">Visualizações</th>
              <th scope="col" class="px-2 py-2"></th>
            </tr>
          </thead>
          <tbody>
            {% for x in blog %}
            <tr
              class="odd:bg-stone-50 even:bg-stone-200 border-b border-gray-200"
            >
              <td scope="row" class="px-2 py-2 whitespace-nowrap">
                {{ x.title }}
              </td>
              <td scope="row" class="px-2 py-2 text-center">
                {% if x.is_anonymous %}<i class="fa-solid fa-check"></i>{% endif %}
              </td>
              <td scope="row" class="px-2 py-2 text-center">
                {% if x.thumbnail %}<i class="fa-solid fa-check"></i>{% endif %}
              </td>
              <td scope="row" class="px-8 py-2">{{ x.create_at|timesince }}</td>
              <td scope="row" class="px-2 py-2 text-center">{{ x.views }}</td>
              <td scope="row" class="px-2 py-2 text-center">
                <a
                  href="{% url 'app:edit_blog' x.pk %}"
                  class="inline-flex items-center justify-center border align-middle select-none font-sans font-medium text-center duration-300 ease-in disabled:opacity-50 disabled:shadow-none disabled:cursor-not-allowed focus:shadow-none text-sm py-2 px-4 shadow-sm hover:shadow-md bg-stone-800 hover:bg-stone-700 relative bg-gradient-to-b from-stone-700 to-stone-800 border-stone-900 text-stone-50 rounded-lg hover:bg-gradient-to-b hover:from-stone-800 hover:to-stone-800 hover:border-stone-900 after:absolute after:inset-0 after:rounded-[inherit] after:box-shadow after:shadow-[inset_0_1px_0px_rgba(255,255,255,0.25),inset_0_-2px_0px_rgba(0,0,0,0.35)] after:pointer-events-none transition antialiased"
                  ><i class="fa-solid fa-pen-to-square"></i
                ></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}